# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

sqrt_double <- function(x) {
    .Call('_longbc_sqrt_double', PACKAGE = 'longbc', x)
}

cppconcat <- function(x, y) {
    .Call('_longbc_cppconcat', PACKAGE = 'longbc', x, y)
}

cppunlist <- function(list) {
    .Call('_longbc_cppunlist', PACKAGE = 'longbc', list)
}

cppuppertosym <- function(m) {
    .Call('_longbc_cppuppertosym', PACKAGE = 'longbc', m)
}

cppnrm2 <- function(x) {
    .Call('_longbc_cppnrm2', PACKAGE = 'longbc', x)
}

cppmatvec <- function(m, v) {
    .Call('_longbc_cppmatvec', PACKAGE = 'longbc', m, v)
}

cppsparsematvec <- function(m, v) {
    .Call('_longbc_cppsparsematvec', PACKAGE = 'longbc', m, v)
}

cppmatinv <- function(m) {
    .Call('_longbc_cppmatinv', PACKAGE = 'longbc', m)
}

cppmatvecold <- function(m, v) {
    .Call('_longbc_cppmatvecold', PACKAGE = 'longbc', m, v)
}

cppl2prox <- function(x, lam) {
    .Call('_longbc_cppl2prox', PACKAGE = 'longbc', x, lam)
}

cppsubju <- function(a, subj, n) {
    .Call('_longbc_cppsubju', PACKAGE = 'longbc', a, subj, n)
}

cppfeatu <- function(a, feat, p) {
    .Call('_longbc_cppfeatu', PACKAGE = 'longbc', a, feat, p)
}

cppaupdate <- function(a, blist, clist, deltalist, etalist, subj, feat, Xty, XtXrhoDeltai, rho) {
    .Call('_longbc_cppaupdate', PACKAGE = 'longbc', a, blist, clist, deltalist, etalist, subj, feat, Xty, XtXrhoDeltai, rho)
}

cppbupdate <- function(a, blist, deltalist, subj, lamlist) {
    .Call('_longbc_cppbupdate', PACKAGE = 'longbc', a, blist, deltalist, subj, lamlist)
}

cppcupdate <- function(a, clist, etalist, feat, lamlist) {
    .Call('_longbc_cppcupdate', PACKAGE = 'longbc', a, clist, etalist, feat, lamlist)
}

cppdupdate <- function(a, blist, deltalist, subj) {
    .Call('_longbc_cppdupdate', PACKAGE = 'longbc', a, blist, deltalist, subj)
}

cppeupdate <- function(a, clist, etalist, feat) {
    .Call('_longbc_cppeupdate', PACKAGE = 'longbc', a, clist, etalist, feat)
}

cppobj <- function(a, subj, feat, m1, m2, lambda, w1, w2, X, y) {
    .Call('_longbc_cppobj', PACKAGE = 'longbc', a, subj, feat, m1, m2, lambda, w1, w2, X, y)
}

cppadmm <- function(a, blist, clist, deltalist, etalist, subj, feat, n, p, X, y, lambda, wsubj, wfeat, wlrsubj, wlrfeat, Xty, XtXrhoDeltai, rho, niter, tolrel, tolabs, trace, loud) {
    .Call('_longbc_cppadmm', PACKAGE = 'longbc', a, blist, clist, deltalist, etalist, subj, feat, n, p, X, y, lambda, wsubj, wfeat, wlrsubj, wlrfeat, Xty, XtXrhoDeltai, rho, niter, tolrel, tolabs, trace, loud)
}

rcppeigen_hello_world <- function() {
    .Call('_longbc_rcppeigen_hello_world', PACKAGE = 'longbc')
}

rcppeigen_outerproduct <- function(x) {
    .Call('_longbc_rcppeigen_outerproduct', PACKAGE = 'longbc', x)
}

rcppeigen_innerproduct <- function(x) {
    .Call('_longbc_rcppeigen_innerproduct', PACKAGE = 'longbc', x)
}

rcppeigen_bothproducts <- function(x) {
    .Call('_longbc_rcppeigen_bothproducts', PACKAGE = 'longbc', x)
}

